# Generated by Django 4.2 on 2024-12-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_remove_questionhistory_user_chatinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatinstance',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
