# Generated by Django 4.2 on 2024-12-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_chatinstance_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
