# Generated by Django 4.2 on 2024-12-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_questionhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionhistory',
            name='response_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
