# Generated by Django 4.2 on 2024-12-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_questionhistory_response_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
